/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author harsh
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Options extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    public Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomsavailButton = new javax.swing.JButton();
        customerdetailButton = new javax.swing.JButton();
        staffdetailButton = new javax.swing.JButton();
        bkaroomButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 0, 0));

        roomsavailButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        roomsavailButton.setText("Room available");
        roomsavailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsavailButtonActionPerformed(evt);
            }
        });

        customerdetailButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        customerdetailButton.setText("Customer Detail");
        customerdetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerdetailButtonActionPerformed(evt);
            }
        });

        staffdetailButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        staffdetailButton.setText("Staff Detail");
        staffdetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffdetailButtonActionPerformed(evt);
            }
        });

        bkaroomButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bkaroomButton.setText("Book a Room");
        bkaroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkaroomButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("  Select :");

        ResetButton.setText("Reset All");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(roomsavailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffdetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bkaroomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerdetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomsavailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerdetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bkaroomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffdetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bkaroomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkaroomButtonActionPerformed
        // TODO add your handling code here:
        new Bk().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bkaroomButtonActionPerformed

    private void roomsavailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsavailButtonActionPerformed
        // TODO add your handling code here:
        RoomAvail obj =new RoomAvail();
        obj.showDetails();
         obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_roomsavailButtonActionPerformed

    private void customerdetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerdetailButtonActionPerformed
        // TODO add your handling code here:
         CustDetails obj =new CustDetails();
         obj.showDetails();
         obj.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_customerdetailButtonActionPerformed

    private void staffdetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffdetailButtonActionPerformed
        // TODO add your handling code here:
         StaffDetails obj =new StaffDetails();
         obj.showDetails();
          obj.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_staffdetailButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        try
        {
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection conn = DriverManager.getConnection("jdbc:sqlserver://BAT\\SQLEXPRESS:1433;databaseName=Hotel;integratedSecurity=true;");
        String q1="truncate table customer;";
        PreparedStatement ps=conn.prepareStatement(q1);
        ps.execute();
        q1="truncate table room;";
        ps=conn.prepareStatement(q1);
        ps.execute();
        q1="update avail set available = 50 where type like 'Standard';";
        conn.prepareStatement(q1).execute();
        q1="update avail set available = 25 where type like 'Premium';";
        conn.prepareStatement(q1).executeUpdate();
        q1="update avail set available = 10 where type like 'Deluxe';";
        conn.prepareStatement(q1).executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Reset Complete"); 
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton bkaroomButton;
    private javax.swing.JButton customerdetailButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton roomsavailButton;
    private javax.swing.JButton staffdetailButton;
    // End of variables declaration//GEN-END:variables
}
