/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author harsh
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class SelectRoom extends javax.swing.JFrame {
    long addhr;
    /**
     * Creates new form SelectRoom
     */
    public SelectRoom() {
        initComponents();
    }
    
    public void set(String s1)
    {
           addhr=Long.parseLong(s1);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StandardComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        PremiumComboBox = new javax.swing.JComboBox<>();
        DeluxeComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        De = new javax.swing.JLabel();
        srBackButton = new javax.swing.JButton();
        confirmbookButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Select Rooms");

        StandardComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Standard");

        PremiumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        PremiumComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumComboBoxActionPerformed(evt);
            }
        });

        DeluxeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        DeluxeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeluxeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Premium");

        De.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        De.setText("Deluxe");

        srBackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        srBackButton.setText("Back");
        srBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srBackButtonActionPerformed(evt);
            }
        });

        confirmbookButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmbookButton.setText("Confirm Booking");
        confirmbookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(201, 201, 201))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StandardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PremiumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(srBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(De, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeluxeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confirmbookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(De, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StandardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PremiumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeluxeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmbookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeluxeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeluxeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeluxeComboBoxActionPerformed

    private void PremiumComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PremiumComboBoxActionPerformed

    private void confirmbookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbookButtonActionPerformed
        // TODO add your handling code here:
        int std,del,pre;
        std=Integer.parseInt((String)StandardComboBox.getSelectedItem());
        pre=Integer.parseInt((String)PremiumComboBox.getSelectedItem());
        del=Integer.parseInt((String)DeluxeComboBox.getSelectedItem()); 
        int astd,adel,apre;
        try
        {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection conn = DriverManager.getConnection("jdbc:sqlserver://BAT\\SQLEXPRESS:1433;databaseName=Hotel;integratedSecurity=true;");
        
        
		String q1 ="select * from avail where type like 'Standard';";    
		PreparedStatement ps=conn.prepareStatement(q1);
		ResultSet rs=ps.executeQuery();
                                        rs.next();
                                       astd=rs.getInt("available");
                                        System.out.println(astd);
		String q2 ="select available from avail where type = 'Premium'";
		ps=conn.prepareStatement(q2); 
		rs=ps.executeQuery();
                                       rs.next();
		apre=Integer.parseInt(rs.getString("available"));
		String q3 ="select available from avail where type = 'Deluxe'";
		ps=conn.prepareStatement(q3);
		rs=ps.executeQuery();
                                        rs.next();
		adel=rs.getInt("available");

        
        
            if(std>astd||pre>apre||del>adel)
            {
                JOptionPane.showMessageDialog(null, "Sorry Rooms not available."); 
                SelectRoom obj= new SelectRoom();
                 obj.set(Long.toString(addhr));
                obj.setVisible(true);
                this.dispose();
                  return;                    
            }
            else
            {
                String nstd=Integer.toString(astd-std);
                String ndel=Integer.toString(adel-del);
                String npre=Integer.toString(apre-pre);
                q1= "update avail set available = "+nstd+" where type like 'Standard'";
                ps=conn.prepareStatement(q1);
                ps.execute();
                q2= "update avail set available = "+npre+" where type like 'Premium'";
                ps=conn.prepareStatement(q2);
                ps.execute();
                q3= "update avail set available = "+ndel+" where type like 'Deluxe'";
                ps=conn.prepareStatement(q3);
                ps.execute();
                 
                
                
                q1="insert into room values(?,?,?,?);";
                ps=conn.prepareStatement(q1);
                ps.setLong(1,addhr);
                ps.setInt(2,std);
                ps.setInt(3,pre);
                ps.setInt(4,del);
                ps.execute(); 
            }
            
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        new Options().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_confirmbookButtonActionPerformed

    private void srBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srBackButtonActionPerformed
        // TODO add your handling code here:
        new Bk().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_srBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel De;
    private javax.swing.JComboBox<String> DeluxeComboBox;
    private javax.swing.JComboBox<String> PremiumComboBox;
    private javax.swing.JComboBox<String> StandardComboBox;
    private javax.swing.JButton confirmbookButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton srBackButton;
    // End of variables declaration//GEN-END:variables
}
